name: smartnextsteps
favicon: null
layout_spectrum: 0.24368
typography_spectrum: 0.24007
title: smartnextsteps
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ecebf1'
    - '#67b5ff'
    - '#040c00'
    - '#2c361d'
    - '#59862b'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
